name: Auto Upload to GitHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Push to GitHub
        run: |
          git config --global user.email "shahanuralam621@gmail.com"
          git config --global user.name "Shahanur Alam"
          git add .
          git commit -m "Auto upload on commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
